ARG BASE_BUILD_IMAGE=debian:10.13

FROM ${BASE_BUILD_IMAGE} as build
RUN echo "Using base image: ${BASE_BUILD_IMAGE}"

WORKDIR /app
# Fix script tput error
ENV TERM=xterm

#ARG DEBIAN_FRONTEND=noninteractive
RUN if [  -e /etc/apt/sources.list ];then sed -ri 's/[a-zA-Z0-9.]+(debian.org|ubuntu.com)/mirrors.aliyun.com/g' /etc/apt/sources.list; fi && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update

COPY . /app/
# build ffmpeg
RUN bash /app/build-ffmpeg.sh ""

FROM scratch AS bin
COPY --from=build /app/ffmpeg-build/ffmpeg512-*.tar.gz /